### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by Ziraeal** [HACKERALERT/Picocrypt#132] opened 2022-10-27 08:14 UTC
Hello.
Picocrypt is a great program.
But I would really like a CLI or TUI version of this program, since the graphical interface is not always available.
I think I'm not the only one who would benefit from such a version.
Thank you.

**Comment by Minibus93** [comment] 2022-11-01 08:48
![image](https://user-images.githubusercontent.com/73554423/199194592-1d121bd2-bd5a-4cbc-8748-f06a9708e253.png)

Duplicate of #14

**Closed** 2022-11-04 15:47 UTC

**Comment by HACKERALERT** [comment] 2022-11-16 23:20
Hi, sorry for the late reply. As Minibus93 has said, a CLI has been requested before, but I don't think it is very useful considering that Picocrypt's main selling point is the UI.

**Comment by Ziraeal** [comment] 2023-04-14 11:25
I am very happy because I have been looking for such a tool for a long time. Thanks for the work you've done. This project deserves 100k stars:)

> @Ziraeal @Minibus93
> 
> In a spark of motivation, I've finally added a simple CLI to Picocrypt! Let me know what you think.
> 
> https://github.com/HACKERALERT/Picocrypt/tree/main/cli
