### ISSUE TITLE
Decrypting to C:\Program Files\ does nothing → confusion (admin permission)

### ISSUE THREAD

**Issue by Inrumpo** [HACKERALERT/Picocrypt#40] opened 2021-09-22 16:20 UTC
I'm currently testing Picocrypt because I like the idea and functionality behind this lightweight tool. I believe my rather "non-techy" perspective can be of value (in terms of expectations and workflow).

## Environment

- Windows 10, 64bit
- Version 1.17 stable

## Description of the issue
Decrypting a `.pcv` file located at `C:\Program Files\Picocrypt` to the same destination (probably anywhere in `C:\Program Files\`) does nothing if `Picocrypt.exe` isn't running with administrator permission.

![Picocrypt decrypting issue](https://user-images.githubusercontent.com/11300164/134379098-9570d350-52ac-4951-b538-ab0c9f2df86c.gif)

This is not a bug, rather a Windows security feature. The user (not knowing this) might be confused because nothing happened; especially after getting the green `Completed.` message. 

## Possible solution
Is it possible to show a hint or even prompt the user to grant administrator permission when decrypting to a "protected" destination?

**Comment by HACKERALERT** [comment] 2021-09-22 19:10
Great catch! I should be able to detect this with a pretty trivial fix. I don't think Go allows to me automatically prompt for permissions, so I guess the user would have to restart Picocrypt. But I will definitely add the hint that there was a permission issue!

**Comment by HACKERALERT** [comment] 2021-09-22 19:57
The issue should be fixed now. Can you confirm that the attached version detects the permission issue on your system? Thanks!
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/7213417/Picocrypt.zip)

**Comment by Inrumpo** [comment] 2021-09-22 20:36
> Can you confirm that the attached version detects the permission issue on your system?

There are multiple combinations possible:

- Decrypting a folder from outside into `C:\Program Files\Picocrypt` shows a permission error by Windows. ✔
- Encrypting a folder from outside into `C:\Program Files\Picocrypt` shows a permission error by Windows. ✔

- Decrypting a folder from `C:\Program Files\Picocrypt` to `C:\Program Files\Picocrypt` into `C:\Program Files\Picocrypt` shows _new error message_ by Picocrypt. ✔
- Encrypting a folder from `C:\Program Files\Picocrypt` to `C:\Program Files\Picocrypt` is not possible. Picocrypt crashes (= same behavior as 1.17). ❌

**Comment by HACKERALERT** [comment] 2021-09-22 20:46
Thanks. I'll fix the last case soon!

**Comment by HACKERALERT** [comment] 2021-09-24 02:25
I put checks on both the input file and output file, so the issue is fixed now :)

**Closed by HACKERALERT** 2021-09-24 02:25 UTC
Labels: enhancement, in progress
