### ISSUE TITLE
pcv file comments get cut off

### ISSUE THREAD

**Issue by DavedZrod** [HACKERALERT/Picocrypt#91] opened 2022-04-27 05:46 UTC
When making an encrypted file, the option to put a comment (read-only) can be written without a length limit. but when you drag the pvc file to the picocrypt window, it gets cut-off.
For example, the comment "this message is going to be cut off because of the window" will only be readable to "~of the w"
![image](https://user-images.githubusercontent.com/90824958/165449280-b5842441-ce56-483c-a24d-b002c30e495e.png)
Im on Windows, Picocrypt version 1.26

**Comment by HACKERALERT** [comment] 2022-04-27 12:15
Thanks for letting me know. So if there is a long comment, what do you suppose should happen?

**Comment by DavedZrod** [comment] 2022-04-28 07:32
Either 1. the message can be selected and copied just like when first making the comment, but not editable  
or 2. the message box should extend to the bottom according to the message length

**Comment by HACKERALERT** [comment] 2022-04-30 03:11
Fixed. You can use the left/right arrow keys to see the entire comment now. Here's a test:
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/8595555/Picocrypt.zip)
Let me know if it works for you, thanks!

**Comment by DavedZrod** [comment] 2022-04-30 08:25
several things i noticed, when using the arrow key the message gets unloaded in chunks upon clicking right arrow,the same happens for creating a comment.
![image](https://user-images.githubusercontent.com/90824958/166097487-fe84107f-9909-4cf4-b77f-cdb38c6064a7.png)
![image](https://user-images.githubusercontent.com/90824958/166097522-f229ff6f-9c48-4c23-9cff-932b0375921f.png)
The comment can only get selected if a password (anything) is inputted otherwise it stays the same
![image](https://user-images.githubusercontent.com/90824958/166098095-9ee535ea-8811-4966-a363-757d174830a5.png)
![image](https://user-images.githubusercontent.com/90824958/166098109-6a6ad650-698d-4c3d-a4cb-9302519f4b67.png) 
I dont know if these are intentional but i just wanted to tell. Other than that, it works, comments do get loaded

**Comment by HACKERALERT** [comment] 2022-05-01 16:27
The unloading in chunks is done by the UI library and there isn't anyway to change that. So it will have to be like that.
I'll fix the commment state during decrypting so it is enabled while decrypting. I'll send a test file when I'm done the fix.

**Comment by HACKERALERT** [comment] 2022-05-01 17:40
[Picocrypt.zip](https://github.com/HACKERALERT/Picocrypt/files/8599412/Picocrypt.zip)
Fixed, please confirm that it works as expected.

**Comment by DavedZrod** [comment] 2022-05-02 05:22
Ok yeah the comments now can get selected before filling in the password. Also sorry i forgot to tell yesterday too that the same thing happens to the Force decrypt, Delete volume, and change output button stays greyed out

**Comment by HACKERALERT** [comment] 2022-05-02 12:39
Can you give a screenshot?

**Comment by DavedZrod** [comment] 2022-05-02 14:47
Before filling password
![image](https://user-images.githubusercontent.com/90824958/166252258-09ac7d91-e7a5-466b-be3f-18332fe5f619.png)
after filling password
![image](https://user-images.githubusercontent.com/90824958/166252177-563362ee-77b2-4544-8048-7ca41accdb95.png)
sorry but i Noticed another thing,

As for the "Save output" message box when making an encrypted file, if i point it to a directory outside of the original file. For example, a file on D:\image with a name abcde.png the box would only show the filename(abcde.png.pcv) and not the directory(not D:\abcde.png.pvc if outside the original folder) and vice versa to decrypting files

It would be also nice to be able to rename the output within the UI in the text (under the Save Output As) rather than needing to open the file explorer UI(for example, typing the directory where the output file is going to be). sorry if this is getting out of topic from the title into feature suggestion

**Comment by HACKERALERT** [comment] 2022-05-02 19:33
Well, you need to put a password before decrypting so it makes sense the options are greyed out when there's no password entered. This is by design.

Storing the entire file path in a small box won't fix. I only show the filename because from my testing, simply dripping a file from my downloads already takes up the entire space. So to keep things clean and the extension visible, only the filename is shown.

The filename is read-only because Picocrypt is a tool where there is only one way to do something. If the filename can be changed with the "Change" button, there's no need to make it editable. And doing so would introduce new bugs such as what do I do if there are invalid characters in the filename? Each system has its own set of valid and invalid characters, and it's best to let the native file dialog handle that.

**Comment by DavedZrod** [comment] 2022-05-03 04:06
Thanks for telling that. Thats all then

**Closed** 2022-05-03 04:07 UTC
